source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.4'

xcodeproj 'GoogleMaps/GoogleMaps.xcodeproj'

target :GoogleMaps, :exclusive => true do
    xcodeproj 'GoogleMaps/GoogleMaps.xcodeproj'
    
	pod 'GoogleMaps'
end
